### POST
POST http://127.0.0.1:5000/api/v1/score HTTP/1.1 
Content-Type: application/json


{
	"name": "blauworanje gele",
	"score": "1500",
    "game": "memory",
	"time": 3
}

### GET
GET http://127.0.0.1:5000/api/v1/score HTTP/1.1
Content-Type: application/json

{
    "game": "memory",
    "time": 3
}